#!/bin/bash

##############################################################################
# Script: cleanup-legacy-companies.sh
# Description: Hapus legacy CompaniesController dan file-file terkait
# Author: Generated for wp-customer cleanup
# Date: 2025-12-30
#
# SAFE DELETE:
# - Membuat backup sebelum hapus
# - Konfirmasi sebelum eksekusi
# - Dry-run option untuk preview
# - Rollback script untuk restore
##############################################################################

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Plugin root directory
PLUGIN_DIR="/home/mkt01/Public/wppm/public_html/wp-content/plugins/wp-customer"
BACKUP_DIR="${PLUGIN_DIR}/backup-legacy-companies-$(date +%Y%m%d-%H%M%S)"

# Dry run flag
DRY_RUN=false
if [[ "$1" == "--dry-run" ]]; then
    DRY_RUN=true
    echo -e "${YELLOW}[DRY RUN MODE] No files will be deleted${NC}\n"
fi

##############################################################################
# Functions
##############################################################################

print_header() {
    echo -e "${BLUE}================================================================${NC}"
    echo -e "${BLUE}  Cleanup Legacy CompaniesController Files${NC}"
    echo -e "${BLUE}================================================================${NC}"
    echo ""
}

print_section() {
    echo -e "\n${GREEN}==> $1${NC}"
}

print_item() {
    echo -e "  ${YELLOW}•${NC} $1"
}

print_success() {
    echo -e "  ${GREEN}✓${NC} $1"
}

print_error() {
    echo -e "  ${RED}✗${NC} $1"
}

check_directory() {
    if [[ ! -d "$PLUGIN_DIR" ]]; then
        print_error "Plugin directory not found: $PLUGIN_DIR"
        exit 1
    fi
    print_success "Plugin directory found: $PLUGIN_DIR"
}

create_backup() {
    print_section "Creating Backup"

    if [[ "$DRY_RUN" == true ]]; then
        print_item "[DRY RUN] Would create backup at: $BACKUP_DIR"
        return 0
    fi

    mkdir -p "$BACKUP_DIR"

    # Backup files that will be deleted
    local files_to_backup=(
        "src/Controllers/Companies"
        "src/Models/Companies"
        "src/Validators/Companies"
        "src/Views/companies"
        "assets/js/companies"
        "assets/css/companies"
    )

    for item in "${files_to_backup[@]}"; do
        local full_path="$PLUGIN_DIR/$item"
        if [[ -e "$full_path" ]]; then
            local backup_path="$BACKUP_DIR/$item"
            mkdir -p "$(dirname "$backup_path")"
            cp -r "$full_path" "$backup_path"
            print_success "Backed up: $item"
        fi
    done

    # Backup wp-customer.php before modification
    if [[ -f "$PLUGIN_DIR/wp-customer.php" ]]; then
        cp "$PLUGIN_DIR/wp-customer.php" "$BACKUP_DIR/wp-customer.php.bak"
        print_success "Backed up: wp-customer.php"
    fi

    print_success "Backup completed at: $BACKUP_DIR"
}

create_rollback_script() {
    print_section "Creating Rollback Script"

    if [[ "$DRY_RUN" == true ]]; then
        print_item "[DRY RUN] Would create rollback script"
        return 0
    fi

    local rollback_script="$BACKUP_DIR/rollback.sh"

    cat > "$rollback_script" << 'EOF'
#!/bin/bash

# Rollback Script - Restore deleted files
# Generated by cleanup-legacy-companies.sh

PLUGIN_DIR="/home/mkt01/Public/wppm/public_html/wp-content/plugins/wp-customer"
BACKUP_DIR="$(dirname "$0")"

echo "==> Restoring files from backup..."

# Restore directories
for item in src/Controllers/Companies src/Models/Companies src/Validators/Companies src/Views/companies assets/js/companies assets/css/companies; do
    if [[ -e "$BACKUP_DIR/$item" ]]; then
        echo "  Restoring: $item"
        cp -r "$BACKUP_DIR/$item" "$PLUGIN_DIR/$item"
    fi
done

# Restore wp-customer.php
if [[ -f "$BACKUP_DIR/wp-customer.php.bak" ]]; then
    echo "  Restoring: wp-customer.php"
    cp "$BACKUP_DIR/wp-customer.php.bak" "$PLUGIN_DIR/wp-customer.php"
fi

echo "==> Rollback completed!"
echo "    Please verify your plugin is working correctly."
EOF

    chmod +x "$rollback_script"
    print_success "Rollback script created: $rollback_script"
}

list_files_to_delete() {
    print_section "Files/Folders to be DELETED"

    echo -e "\n${YELLOW}Folders:${NC}"
    print_item "src/Controllers/Companies/"
    print_item "src/Models/Companies/"
    print_item "src/Validators/Companies/"
    print_item "src/Views/companies/"
    print_item "assets/js/companies/"
    print_item "assets/css/companies/"

    echo -e "\n${YELLOW}Modified Files:${NC}"
    print_item "wp-customer.php (Line 248 - remove CompaniesController instantiation)"

    echo ""
}

delete_folders() {
    print_section "Deleting Legacy Folders"

    local folders=(
        "src/Controllers/Companies"
        "src/Models/Companies"
        "src/Validators/Companies"
        "src/Views/companies"
        "assets/js/companies"
        "assets/css/companies"
    )

    for folder in "${folders[@]}"; do
        local full_path="$PLUGIN_DIR/$folder"

        if [[ -d "$full_path" ]]; then
            if [[ "$DRY_RUN" == true ]]; then
                print_item "[DRY RUN] Would delete: $folder"
            else
                rm -rf "$full_path"
                if [[ $? -eq 0 ]]; then
                    print_success "Deleted: $folder"
                else
                    print_error "Failed to delete: $folder"
                fi
            fi
        else
            print_item "Not found (skipped): $folder"
        fi
    done
}

modify_main_file() {
    print_section "Modifying wp-customer.php"

    local main_file="$PLUGIN_DIR/wp-customer.php"

    if [[ ! -f "$main_file" ]]; then
        print_error "wp-customer.php not found!"
        return 1
    fi

    if [[ "$DRY_RUN" == true ]]; then
        print_item "[DRY RUN] Would remove line 248:"
        print_item "    new \\WPCustomer\\Controllers\\Companies\\CompaniesController();"
        return 0
    fi

    # Remove line 248 (CompaniesController instantiation)
    # Also remove the comment line 247 if it exists
    sed -i.tmp '/Companies Controller (Branch Management with Hook-based System)/,/new \\WPCustomer\\Controllers\\Companies\\CompaniesController();/d' "$main_file"

    if [[ $? -eq 0 ]]; then
        rm "${main_file}.tmp"
        print_success "Removed CompaniesController instantiation from wp-customer.php"
    else
        print_error "Failed to modify wp-customer.php"
        # Restore from backup
        if [[ -f "${main_file}.tmp" ]]; then
            mv "${main_file}.tmp" "$main_file"
        fi
        return 1
    fi
}

verify_cleanup() {
    print_section "Verification"

    local all_clean=true

    # Check folders are deleted
    local folders=(
        "src/Controllers/Companies"
        "src/Models/Companies"
        "src/Validators/Companies"
        "src/Views/companies"
        "assets/js/companies"
        "assets/css/companies"
    )

    for folder in "${folders[@]}"; do
        if [[ -d "$PLUGIN_DIR/$folder" ]]; then
            print_error "Still exists: $folder"
            all_clean=false
        fi
    done

    # Check wp-customer.php doesn't contain CompaniesController
    if grep -q "CompaniesController" "$PLUGIN_DIR/wp-customer.php"; then
        print_error "wp-customer.php still contains CompaniesController reference"
        all_clean=false
    fi

    if [[ "$all_clean" == true ]]; then
        print_success "All legacy files cleaned successfully!"
        return 0
    else
        print_error "Cleanup incomplete - please review manually"
        return 1
    fi
}

show_summary() {
    print_section "Cleanup Summary"

    if [[ "$DRY_RUN" == true ]]; then
        echo -e "${YELLOW}DRY RUN completed - No files were actually deleted${NC}\n"
        echo "To perform actual cleanup, run:"
        echo "  bash cleanup-legacy-companies.sh"
        echo ""
        return 0
    fi

    echo -e "${GREEN}✓ Backup created at:${NC}"
    echo "  $BACKUP_DIR"
    echo ""
    echo -e "${GREEN}✓ Rollback script available at:${NC}"
    echo "  $BACKUP_DIR/rollback.sh"
    echo ""
    echo -e "${YELLOW}Next steps:${NC}"
    echo "  1. Test your plugin functionality"
    echo "  2. Visit: http://wppm.local/wp-admin/admin.php?page=perusahaan"
    echo "  3. Verify CompanyDashboardController works correctly"
    echo ""
    echo -e "${YELLOW}If something breaks:${NC}"
    echo "  bash $BACKUP_DIR/rollback.sh"
    echo ""
}

##############################################################################
# Main Execution
##############################################################################

main() {
    print_header

    # Check plugin directory exists
    check_directory

    # Show what will be deleted
    list_files_to_delete

    # Confirmation (skip in dry-run)
    if [[ "$DRY_RUN" == false ]]; then
        echo -e "${RED}WARNING: This will DELETE the files listed above!${NC}"
        echo -e "${YELLOW}A backup will be created automatically.${NC}\n"
        read -p "Are you sure you want to continue? (yes/no): " confirm

        if [[ "$confirm" != "yes" ]]; then
            echo -e "\n${YELLOW}Cleanup cancelled.${NC}"
            exit 0
        fi
        echo ""
    fi

    # Create backup
    create_backup

    # Create rollback script
    create_rollback_script

    # Delete folders
    delete_folders

    # Modify main file
    modify_main_file

    # Verify cleanup (skip in dry-run)
    if [[ "$DRY_RUN" == false ]]; then
        echo ""
        verify_cleanup
    fi

    # Show summary
    show_summary
}

# Run main function
main

exit 0
