#!/bin/bash

# Rollback Script - Restore deleted files
# Generated by cleanup-legacy-companies.sh

PLUGIN_DIR="/home/mkt01/Public/wppm/public_html/wp-content/plugins/wp-customer"
BACKUP_DIR="$(dirname "$0")"

echo "==> Restoring files from backup..."

# Restore directories
for item in src/Controllers/Companies src/Models/Companies src/Validators/Companies src/Views/companies assets/js/companies assets/css/companies; do
    if [[ -e "$BACKUP_DIR/$item" ]]; then
        echo "  Restoring: $item"
        cp -r "$BACKUP_DIR/$item" "$PLUGIN_DIR/$item"
    fi
done

# Restore wp-customer.php
if [[ -f "$BACKUP_DIR/wp-customer.php.bak" ]]; then
    echo "  Restoring: wp-customer.php"
    cp "$BACKUP_DIR/wp-customer.php.bak" "$PLUGIN_DIR/wp-customer.php"
fi

echo "==> Rollback completed!"
echo "    Please verify your plugin is working correctly."
