<?php
/**
 * Branch Create Form - Modal Template
 *
 * @package     WP_Customer
 * @subpackage  Views/Customer/Branch/Forms
 * @version     1.3.2
 * @author      arisciwek
 *
 * Path: /wp-customer/src/Views/customer/branch/forms/create-branch-form.php
 *
 * Description: Form template for creating new branch via modal.
 *              Loaded via AJAX when Add Branch button clicked.
 *              Integrated with wpAppModal system from wp-app-core.
 *
 * Changelog:
 * 1.3.2 - 2025-11-02 (TODO-2190 Auto-Generate Password)
 * - Removed: Password and password confirmation fields
 * - Changed: Password now auto-generated by WordPress/AutoEntityCreator
 * - Changed: Password sent via email to admin user
 * - Simplified: User only needs username, email, and name
 * - Info box updated to explain auto-generated password
 *
 * 1.3.1 - 2025-11-02 (TODO-2190 Fix Cascade Select)
 * - Fixed: Removed class override to use default wilayah-province-select
 * - Fixed: Removed class override to use default wilayah-regency-select
 * - Added: data-dependent attribute for cascade functionality
 * - Now cascade works: province change → auto-populate regency
 *
 * 1.3.0 - 2025-11-02 (TODO-2190 Use Wilayah Indonesia Hooks)
 * - Changed: Use wilayah_indonesia_province_select action hook
 * - Changed: Use wilayah_indonesia_regency_select action hook
 * - Removed: Hardcoded database queries for provinces/regencies
 * - Benefits: Cache support, consistent with wilayah-indonesia plugin
 *
 * 1.2.0 - 2025-11-02 (TODO-2190 Simplified - No Type Selection)
 * - Removed: Type field (pusat/cabang dropdown)
 * - Added: Info box explaining auto-created pusat branch
 * - Type hardcoded sebagai 'cabang' di controller
 * - Simplified user experience - no confusing type selection
 *
 * 1.0.0 - 2025-11-02 (TODO-2190)
 * - Initial creation
 * - Integrated with wpAppModal system
 * - Branch fields (name, type, contact, location)
 * - Admin user creation support
 */

defined('ABSPATH') || exit;
?>

<form id="branch-form" class="customer-modal-form">
    <input type="hidden" name="action" value="save_branch">
    <input type="hidden" name="mode" value="create">
    <input type="hidden" name="customer_id" value="<?php echo esc_attr($customer_id); ?>">
    <input type="hidden" name="nonce" value="<?php echo wp_create_nonce('wp_customer_nonce'); ?>">

    <h4 style="margin: 0 0 15px 0; font-size: 14px; font-weight: 600; color: #23282d;">
        <?php _e('Informasi Dasar', 'wp-customer'); ?>
    </h4>

    <div class="customer-form-field full-width" style="background: #fff9e6; padding: 10px; border-left: 3px solid #f0b429; margin-bottom: 15px;">
        <p style="margin: 0; font-size: 13px; color: #555;">
            <span class="dashicons dashicons-info" style="color: #f0b429;"></span>
            <?php _e('Cabang Pusat sudah dibuat otomatis saat registrasi customer. Form ini untuk menambah cabang baru.', 'wp-customer'); ?>
        </p>
    </div>

    <div class="customer-form-field">
        <label for="branch-name">
            <?php _e('Nama Cabang', 'wp-customer'); ?>
            <span class="required">*</span>
        </label>
        <input type="text"
               id="branch-name"
               name="name"
               maxlength="100"
               required
               placeholder="<?php esc_attr_e('Masukkan nama lengkap cabang', 'wp-customer'); ?>">
        <span class="description">
            <?php _e('Nama lengkap cabang', 'wp-customer'); ?>
        </span>
    </div>

    <div class="customer-form-field">
        <label for="branch-nitku">
            <?php _e('NITKU', 'wp-customer'); ?>
        </label>
        <input type="text"
               id="branch-nitku"
               name="nitku"
               maxlength="20"
               placeholder="<?php esc_attr_e('Nomor Identitas Tempat Kegiatan Usaha', 'wp-customer'); ?>">
        <span class="description">
            <?php _e('Nomor Identitas Tempat Kegiatan Usaha (optional)', 'wp-customer'); ?>
        </span>
    </div>

    <hr style="margin: 20px 0; border: none; border-top: 1px solid #ddd;">

    <h4 style="margin: 0 0 15px 0; font-size: 14px; font-weight: 600; color: #23282d;">
        <?php _e('Kontak', 'wp-customer'); ?>
    </h4>

    <div class="customer-form-field">
        <label for="branch-phone">
            <?php _e('Telepon', 'wp-customer'); ?>
        </label>
        <input type="text"
               id="branch-phone"
               name="phone"
               maxlength="15"
               pattern="^08[0-9]{8,13}$"
               placeholder="<?php esc_attr_e('08xxxxxxxxxx', 'wp-customer'); ?>">
        <span class="description">
            <?php _e('Format: 08xxxxxxxxxx (08 diikuti 8-13 digit angka)', 'wp-customer'); ?>
        </span>
    </div>

    <div class="customer-form-field">
        <label for="branch-email">
            <?php _e('Email', 'wp-customer'); ?>
        </label>
        <input type="email"
               id="branch-email"
               name="email"
               maxlength="100"
               placeholder="<?php esc_attr_e('branch@company.com', 'wp-customer'); ?>">
        <span class="description">
            <?php _e('Email operasional cabang', 'wp-customer'); ?>
        </span>
    </div>

    <hr style="margin: 20px 0; border: none; border-top: 1px solid #ddd;">

    <h4 style="margin: 0 0 15px 0; font-size: 14px; font-weight: 600; color: #23282d;">
        <?php _e('Alamat & Lokasi', 'wp-customer'); ?>
    </h4>

    <div class="customer-form-field full-width">
        <label for="branch-address">
            <?php _e('Alamat', 'wp-customer'); ?>
            <span class="required">*</span>
        </label>
        <textarea id="branch-address"
                  name="address"
                  rows="3"
                  required
                  placeholder="<?php esc_attr_e('Alamat lengkap cabang', 'wp-customer'); ?>"></textarea>
        <span class="description">
            <?php _e('Alamat lengkap kantor/cabang', 'wp-customer'); ?>
        </span>
    </div>

    <div class="customer-form-field">
        <label for="branch-provinsi">
            <?php _e('Provinsi', 'wp-customer'); ?>
            <span class="required">*</span>
        </label>
        <?php
        // Gunakan hook dari wilayah-indonesia plugin
        // Jangan override class default agar JavaScript cascade berfungsi
        do_action('wilayah_indonesia_province_select', [
            'name' => 'province_id',
            'id' => 'branch-provinsi',
            'required' => true
        ], null);
        ?>
        <span class="description">
            <?php _e('Provinsi lokasi cabang', 'wp-customer'); ?>
        </span>
    </div>

    <div class="customer-form-field">
        <label for="branch-regency">
            <?php _e('Kota/Kabupaten', 'wp-customer'); ?>
            <span class="required">*</span>
        </label>
        <?php
        // Gunakan hook dari wilayah-indonesia plugin
        // data-dependent menghubungkan dengan province select untuk cascade
        do_action('wilayah_indonesia_regency_select', [
            'name' => 'regency_id',
            'id' => 'branch-regency',
            'data-dependent' => 'branch-provinsi',
            'required' => true,
            'disabled' => true
        ], null, null);
        ?>
        <span class="description">
            <?php _e('Kota/Kabupaten lokasi cabang', 'wp-customer'); ?>
        </span>
    </div>

    <div class="customer-form-field">
        <label for="branch-postal-code">
            <?php _e('Kode Pos', 'wp-customer'); ?>
        </label>
        <input type="text"
               id="branch-postal-code"
               name="postal_code"
               maxlength="5"
               placeholder="<?php esc_attr_e('12345', 'wp-customer'); ?>">
        <span class="description">
            <?php _e('Kode pos (5 digit)', 'wp-customer'); ?>
        </span>
    </div>

    <div class="customer-form-field full-width">
        <label><?php _e('Pilih Lokasi di Peta', 'wp-customer'); ?></label>
        <div class="branch-coordinates-map" style="height: 300px; margin-bottom: 15px; border: 1px solid #ddd; border-radius: 4px;"></div>
        <span class="description">
            <?php _e('Klik pada peta atau drag marker untuk menentukan lokasi', 'wp-customer'); ?>
        </span>
    </div>

    <div class="customer-form-field">
        <label for="branch-latitude">
            <?php _e('Latitude', 'wp-customer'); ?>
        </label>
        <input type="text"
               id="branch-latitude"
               name="latitude"
               step="any"
               placeholder="-6.2088">
        <span class="description">
            <?php _e('Koordinat latitude (optional)', 'wp-customer'); ?>
        </span>
    </div>

    <div class="customer-form-field">
        <label for="branch-longitude">
            <?php _e('Longitude', 'wp-customer'); ?>
        </label>
        <input type="text"
               id="branch-longitude"
               name="longitude"
               step="any"
               placeholder="106.8456">
        <span class="description">
            <?php _e('Koordinat longitude (optional)', 'wp-customer'); ?>
        </span>
    </div>

    <div class="customer-form-field full-width">
        <a href="#"
           class="google-maps-link button button-secondary"
           target="_blank"
           style="display: none;">
            <span class="dashicons dashicons-location"></span>
            <?php _e('Lihat di Google Maps', 'wp-customer'); ?>
        </a>
    </div>

    <hr style="margin: 20px 0; border: none; border-top: 1px solid #ddd;">

    <h4 style="margin: 0 0 15px 0; font-size: 14px; font-weight: 600; color: #23282d;">
        <?php _e('Admin Branch', 'wp-customer'); ?>
    </h4>

    <div class="customer-form-field full-width" style="background: #f0f6fc; padding: 10px; border-left: 3px solid #2271b1; margin-bottom: 15px;">
        <p style="margin: 0; font-size: 13px; color: #555;">
            <span class="dashicons dashicons-info" style="color: #2271b1;"></span>
            <?php _e('User admin branch akan dibuat otomatis dengan password yang di-generate sistem. Password akan dikirim via email dan harus diganti saat login pertama kali.', 'wp-customer'); ?>
        </p>
    </div>

    <div class="customer-form-field">
        <label for="admin-username">
            <?php _e('Username', 'wp-customer'); ?>
            <span class="required">*</span>
        </label>
        <input type="text"
               id="admin-username"
               name="admin_username"
               required
               autocomplete="off"
               placeholder="<?php esc_attr_e('Username untuk login', 'wp-customer'); ?>">
        <span class="description">
            <?php _e('Username untuk login admin branch (huruf kecil, angka, underscore)', 'wp-customer'); ?>
        </span>
    </div>

    <div class="customer-form-field">
        <label for="admin-email">
            <?php _e('Email Admin', 'wp-customer'); ?>
            <span class="required">*</span>
        </label>
        <input type="email"
               id="admin-email"
               name="admin_email"
               required
               autocomplete="off"
               placeholder="<?php esc_attr_e('admin@company.com', 'wp-customer'); ?>">
        <span class="description">
            <?php _e('Email untuk menerima password dan notifikasi', 'wp-customer'); ?>
        </span>
    </div>

    <div class="customer-form-field">
        <label for="admin-firstname">
            <?php _e('Nama Depan', 'wp-customer'); ?>
            <span class="required">*</span>
        </label>
        <input type="text"
               id="admin-firstname"
               name="admin_firstname"
               required
               autocomplete="off"
               placeholder="<?php esc_attr_e('Nama depan admin', 'wp-customer'); ?>">
    </div>

    <div class="customer-form-field">
        <label for="admin-lastname">
            <?php _e('Nama Belakang', 'wp-customer'); ?>
        </label>
        <input type="text"
               id="admin-lastname"
               name="admin_lastname"
               autocomplete="off"
               placeholder="<?php esc_attr_e('Nama belakang admin', 'wp-customer'); ?>">
        <span class="description">
            <?php _e('Nama belakang admin (optional)', 'wp-customer'); ?>
        </span>
    </div>
</form>
